---
# template tasks file

- name: apt install software
  apt:
    update_cache: true
    pkg:
    - postgresql
    - postgresql-contrib
#    - phppgadmin
    - libpq-dev
    - python3-pip

- name: install python libraries
  pip:
    name: psycopg2

- name: create postgres wifimon user
  become_user: postgres
  become: yes
  become_method: sudo
  postgresql_user:
    name: wifimon_user
    password: "wifmonpass"

